# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('location', models.CharField(max_length=64)),
                ('subject', models.CharField(max_length=64)),
                ('camera', models.CharField(default='Olympus', max_length=32)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('date', models.DateField(verbose_name='date taken')),
            ],
        ),
    ]
